# <h1>Loops in Python</h1>

<p><strong>Welcome!</strong> This notebook will teach you about the loops in the Python Programming Language. By the end of this lab, you'll know how to use the loop statements in Python, including for loop, and while loop.</p>

# <h2 id="loop">Loops</h2>

## <h3 id="range">Range</h3>

Sometimes, you might want to repeat a given operation many times. Repeated executions like this are performed by <b>loops</b>. We will look at two types of loops, <code>for</code> loops and <code>while</code> loops.

Before we discuss loops lets discuss the <code>range</code> object. It is helpful to think of the range object as an ordered list. For now, let's look at the simplest case. If we would like to generate a sequence that contains three elements ordered from 0 to 2 we simply use the following command:

In [1]:
# Use the range

range(3)

range(0, 3)

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsRange.png" width="300" />

## <h3 id="for">What is <code>for</code> loop?</h3>

The <code>for</code> loop enables you to execute a code block multiple times. For example, you would use this if you would like to print out every element in a list.    
Let's try to use a <code>for</code> loop to print all the years presented in the list <code>dates</code>:

This can be done as follows:

In [2]:
# For loop example

dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
    print(dates[i])

1982
1980
1973

The code in the indent is executed <code>N</code> times, each time the value of <code>i</code> is increased by 1 for every execution. The statement executed is to <code>print</code> out the value in the list at index <code>i</code> as shown here:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForRange.gif" width="800" />

In this example we can print out a sequence of numbers from 0 to 7:

In [3]:
# Example of for loop

for i in range(0, 8):
    print(i)

0
1
2
3
4
5
6
7

In Python we can directly access the elements in the list as follows:

In [4]:
# Exmaple of for loop, loop through list

for year in dates:
    print(year)

1982
1980
1973

For each iteration, the value of the variable <code>years</code> behaves like the value of <code>dates[i]</code> in the  first example:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForList.gif" width="800">

We can change the elements in a list:

In [5]:
# Use for loop to change the elements in list

squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0, 5):
    print("Before square ", i, 'is',  squares[i])
    squares[i] = 'weight'
    print("After square ", i, 'is',  squares[i])

Before square  0 is red
After square  0 is weight
Before square  1 is yellow
After square  1 is weight
Before square  2 is green
After square  2 is weight
Before square  3 is purple
After square  3 is weight
Before square  4 is blue
After square  4 is weight

 We can access the index and the elements of a list as follows:

In [6]:
# Loop through the list and iterate on both index and element value

squares=['red', 'yellow', 'green', 'purple', 'blue']

for i, square in enumerate(squares):
    print(i, square)

0 red
1 yellow
2 green
3 purple
4 blue

## <h3 id="while">What is <code>while</code> loop?</h3>

As you can see, the <code>for</code> loop is used for a controlled flow of repetition. However, what if we don't know when we want to stop the loop? What if we want to keep executing a code block until a certain condition is met? The <code>while</code> loop exists as a tool for repeated execution based on a condition. The code block will keep being executed until the given logical condition returns a **False** boolean value.

Letâ€™s say we would like to iterate through list <code>dates</code> and stop at the year 1973, then print out the number of iterations. This can be done with the following block of code:

In [7]:
# While Loop Example

dates = [1982, 1980, 1973, 2000]

i = 0
year = 0

while(year != 1973):
    year = dates[i]
    i = i + 1
    print(year)

print("It took ", i ,"repetitions to get out of loop.")

1982
1980
1973
It took  3 repetitions to get out of loop.

A while loop iterates merely until the condition in the argument is not  met, as shown in the following figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsWhile.gif" width="650" />

<hr>

# <h2 id="NestedLoop">Nested Loop</h2>

A nested loop is a loop inside the body of the outer loop. The inner or outer loop can be any type, such as a <code> while loop </code> or <code> for loop </code>. For example, the outer <code>for</code> loop can contain a <code>while</code> loop and vice versa.

The outer loop can contain more than one inner loop. There is no limitation on the chaining of loops.

In the nested loop, the number of iterations will be equal to the number of iterations in the outer loop multiplied by the iterations in the inner loop.

In each iteration of the outer loop inner loop execute all its iteration. <b>For each iteration of an outer loop the inner loop re-start and completes its execution</b> before the outer loop can continue to its next iteration.

Nested loops are typically used for working with multidimensional data structures, such as printing two-dimensional arrays, iterating a list that contains a nested list.

**Syntax of using a nested for loop in Python :**

<pre>
# outer for loop
for element in sequence
   # inner for loop
   for element in sequence:
       body of inner for loop
   body of outer for loop
</pre>

In this example, we are using a <code>for</code> loop inside a <code>for</code> loop. In this example, we are <b>printing a multiplication table</b> of the first ten numbers.

*   The outer <code>for</code> loop uses the range() function to iterate over the first ten numbers
*   The inner <code>for</code> loop will execute ten times for each outer number
*   In the body of the inner loop, we will print the multiplication of the outer number and current number
*   The inner loop is nothing but a body of an outer loop.

![image.png]()

**Example:** Write a nested for loop program to print multiplication table in Python

In [8]:
# outer loop
for i in range(1, 11):
    # nested loop
    # to iterate from 1 to 10
    for j in range(1, 11):
        # print multiplication
        print(i * j, end=' ')
    print()

1 2 3 4 5 6 7 8 9 10
2 4 6 8 10 12 14 16 18 20
3 6 9 12 15 18 21 24 27 30
4 8 12 16 20 24 28 32 36 40
5 10 15 20 25 30 35 40 45 50
6 12 18 24 30 36 42 48 54 60
7 14 21 28 35 42 49 56 63 70
8 16 24 32 40 48 56 64 72 80
9 18 27 36 45 54 63 72 81 90
10 20 30 40 50 60 70 80 90 100



*   In this program, the outer <code>for</code> loop is iterate numbers from 1 to 10. The <code>range()</code> return 10 numbers. So total number of iteration of the outer loop is 10.
*   In the first iteration of the nested loop, the number is 1. In the next, it 2. and so on till 10.
*   Next, For each iteration of the outer loop, the inner loop will execute ten times. The inner loop will also execute ten times because we are printing multiplication table up to ten.
*   In each iteration of an inner loop, we calculated the multiplication of two numbers.

## <h3 id="WhileInsideForLoop">While Loop Inside a For Loop</h2>

It is very common and helpful to use one type of loop inside another. we can put a <code>while</code> loop inside the <code>for</code> loop.

Assume we wanted to repeat each name from a list five times.
*   Here we will iterate the list using an outer <code>for</code> loop
*   In each iteration of outer <code>for</code> loop, the inner <code>for</code> loop execute five times to print the current name five times

In [9]:
names = ['Kelly', 'Jessa', 'Emma']
# outer loop
for name in names:
    # inner while loop
    count = 0
    while count < 5:
        print(name, end=' ')
        # increment counter
        count = count + 1
    print()

Kelly Kelly Kelly Kelly Kelly
Jessa Jessa Jessa Jessa Jessa
Emma Emma Emma Emma Emma

## <h3 id="BreakNestedLoop">Break Nested Loop</h2>

The <code>break</code> statement is used inside the loop to exit out of the loop. If the <code>break</code> statement is used inside a nested loop (loop inside another loop), it will terminate the innermost loop.

In the following example, we have two loops. The outer <code>for</code> loop iterates the first four numbers using the <code>range()</code> function, and the inner <code>for</code> loop also iterates the first four numbers. If the **outer number and a current number of the inner loop** are the same, then break the inner (nested) loop.

**Example :**

In [10]:
for i in range(4):
    for j in range(4):
        if j == i:
            break
        print(i, j)

1 0
2 0
2 1
3 0
3 1
3 2

As you can see in the output, no rows contain the same number.

## <h3 id="ContinueNestedLoop">Continue Nested Loop</h2>

The <code>continue</code> statement skip the current iteration and move to the next iteration. In Python, when the <code>continue</code> statement is encountered inside the loop, it skips all the statements below it and immediately jumps to the next iteration.

In the following example, we have two loops. The outer for loop iterates the first list, and the inner loop also iterates the second list of numbers.

If the outer number and the inner loopâ€™s current number are the same, then move to the next iteration of an inner loop.

**Example:**

In [11]:
first = [2, 4, 6]
second = [2, 4, 6]
for i in first:
    for j in second:
        if i == j:
            continue
        print(i, '*', j, '= ', i * j)

2 * 4 =  8
2 * 6 =  12
4 * 2 =  8
4 * 6 =  24
6 * 2 =  12
6 * 4 =  24

As you can see in the output, no same numbers multiplying to each other.

## <h3 id="NestedWhileLoop">Nested While Loop</h3>

In Python, The <code>while</code> loop statement repeatedly executes a code block <code>while</code> a particular condition is true. We use a <code>while</code> loop when number iteration is not fixed.

In this section, we will see how to use a <code>while</code> loop inside another <code>while</code> loop.

The syntax to write a **nested while loop** statement in Python is as follows:

<pre>
while expression:
   while expression:
      statement(s)
   statement(s)
</pre>

**Example:**

In this example, we will print the first 10 numbers on each line 5 times.

In [12]:
i = 1
while i <= 5:
    j = 1
    while j <= 10:
        print(j, end='')
        j = j + 1
    i = i + 1
    print()

12345678910
12345678910
12345678910
12345678910
12345678910

## <h3 id="ForLoopInsideWhileLoop">For Loop Inside While Loop</h3>

Sometimes it is helpful to use one type of loop inside another. we can put a <code>for</code> loop inside the <code>while</code> loop.

Assume we wanted to **print all perfect numbers from 1 to 100**

Here we will iterate the first 100 numbers using a <code>while</code> loop
In each iteration of the outer <code>while</code> loop, the inner <code>for</code> loop execute from 1 up to the current outer number to check if the current number is a perfect number.

In [13]:
print('Show Perfect number fom 1 to 100')
n = 2
# outer while loop
while n <= 100:
    x_sum = 0
    # inner for loop
    for i in range(1, n):
        if n % i == 0:
            x_sum += i
    if x_sum == n:
        print('Perfect number:', n)
    n += 1

Show Perfect number fom 1 to 100
Perfect number: 6
Perfect number: 28

# <h2 id="quiz">Quiz on Loops</h2>

Write a <code>for</code> loop the prints out all the element between <b>-5</b> and <b>5</b> using the range function.

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.
<!--
for i in range(-5, 6):
    print(i)
-->

Print the elements of the following list:
<code>Genres=[ 'rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']</code>
Make sure you follow Python conventions.

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.
<!--
Genres = ['rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']
for Genre in Genres:
    print(Genre)
-->

<hr>

Write a for loop that prints out the following list: <code>squares=['red', 'yellow', 'green', 'purple', 'blue']</code>

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.
<!--
squares=['red', 'yellow', 'green', 'purple', 'blue']
for square in squares:
    print(square)
 -->

<hr>

Write a while loop to display the values of the Rating of an album playlist stored in the list <code>PlayListRatings</code>. If the score is less than 6, exit the loop. The list <code>PlayListRatings</code> is given by: <code>PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]</code>

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.
<!--
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i = 1
Rating = PlayListRatings[0]
while(Rating >= 6):
    print(Rating)
    Rating = PlayListRatings[i]
    i = i + 1
 -->

<hr>

Write a while loop to copy the strings <code>'orange'</code> of the list <code>squares</code> to the list <code>new_squares</code>. Stop and exit the loop if the value on the list is not <code>'orange'</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute

Double-click __here__ for the solution.
<!--
squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []
i = 0
while(squares[i] == 'orange'):
    new_squares.append(squares[i])
    i = i + 1
print (new_squares)
 -->

<hr>

## <h3 id="WeeklyExercise1">Weekly Exercise 1</h3>

Buatlah kode program untuk dapat menampilkan sebagai berikut :

<pre>
     *
    * *
   * * *
  * * * *
 * * * * *
* * * * * *
</pre>

Jumlah baris pada gambar di atas berdasarkan angka yang dimasukkan oleh user.

<br>
Sebagai contoh, apabila user memasukkan angka 2, maka tampilan menjadi:
<pre>
 *
* *
</pre>

<br>
Apabila user memasukkan angka 3, maka tampilan menjadi:
<pre>
  *
 * *
* * *
</pre>

## <h3 id="WeeklyExercise2">Weekly Exercise 2</h3>

Buatlah kode program untuk dapat menampilkan segitiga pascal sebagai berikut :

<pre>
     1
    1 1
   1 2 1
  1 3 3 1
 1 4 6 4 1
</pre>

Jumlah baris pada gambar di atas berdasarkan angka yang dimasukkan oleh user.

<br>
Sebagai contoh, apabila user memasukkan angka 2, maka tampilan menjadi:
<pre>
 1
1 1
</pre>

<br>
Apabila user memasukkan angka 3, maka tampilan menjadi:
<pre>
  1
 1 1
1 2 1
</pre>

## <h3 id="WeeklyExercise3">Weekly Exercise 3</h3>

Buatlah kode program untuk dapat menampilkan jumlah angka dalam satu baris segitiga pascal.

Sebagai contoh, apabila user memasukkan angka 2, maka angka dalam satu baris segitiga pascal adalah:
<pre>
1 1
</pre>

Sehingga perlu menjumlahkan 1 + 1, maka output dari program adalah 2


Apabila user memasukkan angka 3, maka angka dalam satu baris segitiga pascal adalah:
<pre>
1 2 1
</pre>
Sehingga perlu menjumlahkan 1 + 2 + 1, maka output dari program adalah 4

<hr>

<p>Copyright &copy; Prodi Teknologi Informasi -  Universitas Tidar.</p>